apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mediaserver.fullname" . }}-plex-claim0
  labels:
    io.kompose.service: plex-claim0
  {{- include "mediaserver.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
status: {}