on:
  push:
    branches:
      - gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          helm repo add xerktech https://charts.xerktech.com
          helm dependency update

      - name: Install aws-cli
        run: |
          apk --no-cache add aws-cli --repository=http://dl-cdn.alpinelinux.org/alpine/v3.10/community

      - name: Deploy to Kubernetes
        uses: deliverybot/helm@master
        with:
          chart: mediaserver
          repository: https://charts.xerktech.com
          namespace: dev
          release: mediaserver-release
          values: |
            $(cat ./dev.values.yaml)
