name: Helm Install - Dev

on:
  push:
    branches:
      - gh-pages

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Deploy to Kubernetes
        uses: deliverybot/helm@master
        with:
          chart: mediaserver
          repository: https://charts.xerktech.com
          namespace: dev
          release: mediaserver-release
          values: |
            $(cat ./dev.values.yaml)
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'
