name: Helm Install - Dev

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
#       - name: Wait for 30 seconds
#         run: sleep 30

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Remove from Kubernetes
        uses: vimeda/helm@v1.6.8
        with:
          chart: xerhab/mediaserver
          repo: https://charts.xerktech.com
          repo-alias: xerhab
          namespace: dev
          release: mediaserver
          value-files: dev.values.yaml
          task: remove
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'
      
      - name: Deploy to Kubernetes
        uses: vimeda/helm@v1.6.8
        with:
          chart: xerhab/mediaserver
          repo: https://charts.xerktech.com
          repo-alias: xerhab
          namespace: dev
          release: mediaserver
          value-files: dev.values.yaml
          task: install
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'
