name: Helm Install - Dev

on:
  push:
    branches:
      - gh-pages

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: gh-pages
      
#       - name: Add Helm repository
#         run: |
#           helm repo add xerhab https://charts.xerktech.com
#           helm repo update

      - name: Deploy to Kubernetes
        uses: vimeda/helm@v1.6.8
        with:
          chart: xerhab/mediaserver
          chart-version: latest
          repo: https://charts.xerktech.com
          repo-alias: xerhab
          namespace: dev
          release: mediaserver
          value-files: dev.values.yaml
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'
